import type { AchievementDef } from '../types';

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    key: 'first_win',
    name: 'First Blood',
    emoji: '🩸',
    description: 'Win your first match',
    check: (s) => s.wins >= 1,
  },
  {
    key: 'five_wins',
    name: 'High Five',
    emoji: '🖐️',
    description: 'Win 5 matches',
    check: (s) => s.wins >= 5,
  },
  {
    key: 'ten_wins',
    name: 'Double Digits',
    emoji: '🔟',
    description: 'Win 10 matches',
    check: (s) => s.wins >= 10,
  },
  {
    key: 'twenty_five_wins',
    name: 'Quarter Century',
    emoji: '💎',
    description: 'Win 25 matches',
    check: (s) => s.wins >= 25,
  },
  {
    key: 'fifty_wins',
    name: 'Half Century',
    emoji: '🏅',
    description: 'Win 50 matches',
    check: (s) => s.wins >= 50,
  },
  {
    key: 'streak_3',
    name: 'On Fire',
    emoji: '🔥',
    description: 'Win 3 matches in a row',
    check: (s) => s.maxStreak >= 3,
  },
  {
    key: 'streak_5',
    name: 'Unstoppable',
    emoji: '💪',
    description: 'Win 5 matches in a row',
    check: (s) => s.maxStreak >= 5,
  },
  {
    key: 'streak_10',
    name: 'Legendary',
    emoji: '🐉',
    description: 'Win 10 matches in a row',
    check: (s) => s.maxStreak >= 10,
  },
  {
    key: 'giant_killer',
    name: 'Giant Killer',
    emoji: '🐲',
    description: 'Beat someone with 200+ higher Elo',
    check: (s) => s.biggestUpset >= 200,
  },
  {
    key: 'comeback_kid',
    name: 'Comeback Kid',
    emoji: '🦸',
    description: 'Win a match after losing the first set',
    check: (s) => s.comebacks >= 1,
  },
  {
    key: 'elo_1200',
    name: 'Rising Star',
    emoji: '⭐',
    description: 'Reach 1200 Elo',
    check: (s) => s.elo >= 1200,
  },
  {
    key: 'elo_1400',
    name: 'Challenger',
    emoji: '⚡',
    description: 'Reach 1400 Elo',
    check: (s) => s.elo >= 1400,
  },
  {
    key: 'elo_1600',
    name: 'Masters Level',
    emoji: '🏆',
    description: 'Reach 1600 Elo',
    check: (s) => s.elo >= 1600,
  },
  {
    key: 'elo_2000',
    name: 'Grand Slam',
    emoji: '👑',
    description: 'Reach 2000 Elo',
    check: (s) => s.elo >= 2000,
  },
  {
    key: 'played_10',
    name: 'Regular',
    emoji: '📅',
    description: 'Play 10 matches',
    check: (s) => s.matchesPlayed >= 10,
  },
  {
    key: 'played_50',
    name: 'Veteran',
    emoji: '🎖️',
    description: 'Play 50 matches',
    check: (s) => s.matchesPlayed >= 50,
  },
];
